### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [tyrasd/nominatim-specialphrases-typos#1]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project [seems to be using osmosis](https://github.com/tyrasd/nominatim-specialphrases-typos/search?q=%22http%3A%2F%2Fplanet.openstreetmap.org%22+osmosis), which [will not follow redirects by default](https://trac.openstreetmap.org/ticket/5483).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https? All services respond over https and will start redirecting soon.

**Comment by tyrasd** [comment]
Hi, thanks for the notice, but this repo doesn't actually use either osmosis nor files from planet.osm.org.
Also, this repo (in it's current state) doesn't seem to work anymore because of some upstream changes (in taginfo) and at the moment I don't plan to maintain it anymore.
